### ISSUE TITLE
Adding event dispatcher for when the views change.

### ISSUE THREAD

**Issue by ch222kv** [no222bd/1dv411-Webbprojekt-1#109]
To be able for the UI to render a view in the menu it has to use an image. But there is no way for the UI to know when the views have changed, and as such no way to know when to render the image again. If we want this feature, there needs to be some way for the ConstructionArea to tell the UI when it has done something.

**Comment by davidsoderberg** [comment]
A callback function from the ui maybe?

**Comment by ch222kv** [comment]
Isn't it just easier to dispatch events? If you have a callback you need to pass it from CubeBuilder onto ConstructionArea and then you need to call it from there, but if you have events ConstructionArea just needs to dispatch an event to the canvas or something and the UI can respond to that. I think that would make more sense from a code point of view, since events are so prominent in Javascript.

**Comment by davidsoderberg** [comment]
There is now a branch called issue-109 with an event in Builder.js called "updateView", that are called when a cube has been added or removed. There is also a listener in navigation.js.
