### ISSUE TITLE
When cube is selected the eraser should be less visible in color and vice versa

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#115]
CSS class chosen should mark the chosen buildoption by highlighting the chosen and darkening the non-chosen option. (Jorryts kommentarer 2015-02-18)

**Comment by mn22nw** [comment]
An idea could be to lower the opacity on eraser when the cube is selected & vice versa. ?

**Comment by davidsoderberg** [comment]
Please merge my pull-request :smile:

**Comment by davidsoderberg** [comment]
Fixed in commit: https://github.com/no222bd/1dv411-Webbprojekt-1/commit/846f01fa8f36873d9f2d2ab82c6107ed2562b407.
