### ISSUE TITLE
Placeholder positioned between tiles when page opens.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#13]
When you first open the page the placeholder cube is placed between tiles. Is better if the cube is positioned in a correct position when you open the page.

**Comment by davidsoderberg** [comment]
Placeholder was removed in commit: https://github.com/no222bd/1dv411-Webbprojekt-1/commit/ef7806364460a5ddead202acb49c9c3669614312
Placeholder are not used in customers example.
