### ISSUE TITLE
View in menu doesn't work in Firefox - flashes.

### ISSUE THREAD

**Issue by ch222kv** [no222bd/1dv411-Webbprojekt-1#133]
It only updates when you switch view, not when you click to add cubes. 
The TypeError about p.indexOf doesn't seem to have anything to do with this, because it gets reported everytime you click, not just when you have a view displayed.

**Comment by davidsoderberg** [comment]
Maybe my event implementations not works in all browsers.

**Comment by ch222kv** [comment]
Maybe try using jQuery events instead of ordinary events?

**Comment by ch222kv** [comment]
It seems to work using ```jQuery.Event("updateView")``` instead of ```new CustomEvent("updateView")``` but but the view flashes for just a fraction of a second when it does, so it isn't optimal on Firefox yet.

**Comment by aseea** [comment]
It doesn't work in IE11 either for the same reason.

**Comment by aseea** [comment]
Created a branch for this issue and changed the event like ch222kv suggested which works for IE but still flashes in FF.

**Comment by aseea** [comment]
Status on this when we have views to the right?

**Comment by aseea** [comment]
This doesn't occur for me when the views are moved to the right side of the screen.

**Comment by ch222kv** [comment]
Which would make sense since it's the actual canvas elements and not images rendered from those elements.

**Comment by aseea** [comment]
Closing this issue because of layout change.
