### ISSUE TITLE
Settings-icons in modal are too big on screen format 16:9

### ISSUE THREAD

**Issue by mn22nw** [no222bd/1dv411-Webbprojekt-1#139]
They don't fit vertically in the modal window.

**Comment by ch222kv** [comment]
They do fit in my screen, 1920x1080. What screen size are you seeing this problem on? From basic resizing of the browser it seems like the settings modal gets too big if the screen is 2:1, which I don't think exist,

**Comment by davidsoderberg** [comment]
Fixed in commit: https://github.com/no222bd/1dv411-Webbprojekt-1/commit/3d12a3cd9ad4ebe8ce6b04ea6ba807506729e8ed.
