### ISSUE TITLE
Cube is added on mouseup when rotating the object in FF.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#15]
A new cube is added on every mouseup event inside the grid. This means that if you use the mouse to rotate the object a new cube will be added when you are done rotating. A new cube should only be added when you click on a tile, not when you are rotating the object.

**Comment by ba222ec** [comment]
Happends only in FireFox.

**Comment by davidsoderberg** [comment]
Fixed in commit: https://github.com/no222bd/1dv411-Webbprojekt-1/commit/8841936371ee4f52408ee832e7cc1d5060a9015a
