### ISSUE TITLE
loadModel uses setHex instead of using texture.

### ISSUE THREAD

**Issue by ch222kv** [no222bd/1dv411-Webbprojekt-1#183]
The ```BUILDER.loadModel``` function uses ```material.color.setHex()``` instead of using the ```BUILDER.setCubeMaterial``` function that sets cubeMaterial. This seems kinda hacky, right?

**Comment by ba222ec** [comment]
Yes, that's why we have issue 180. We need to update BUILDER.loadModel and BUILDER.saveModel to use textures instead of colors.

**Comment by davidsoderberg** [comment]
I have fixed this :smile:
