### ISSUE TITLE
The views/perspectives are mirrored (all of the sides) and they are mixed up with each other ?

### ISSUE THREAD

**Issue by mn22nw** [no222bd/1dv411-Webbprojekt-1#194]
Showing the wrong sides for green and red.   (green should be red and vice versa) 
Showing the wrong side for blue and orange. (blue shoud be orange and vice versa)

**Comment by mn22nw** [comment]
Demo of this issue can be found here: 
https://www.dropbox.com/s/ugsqxyw6tln37wj/views.webm?dl=0 
( I had no microphone so it's without sound)

**Comment by aseea** [comment]
Feels like this issue is connected to issue #191.

**Comment by ch222kv** [comment]
This issue is handed off to #232 and #211 because the views aren't longer mirrored, but the lines get drawn in odd order it seems.
