### ISSUE TITLE
Buttons in Resize modal should have centered text.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#207]
In *Resize modal*, the button's text should be vertically centred.

**Comment by aseea** [comment]
iOS, Safari, Surfplatta: "pilar och text är inte jämt fördelade. Om jag roterar från portrait-mode till landscape mode, tillbaka till portrait-mode, hamnar pilarna och rensa knappen utanför deras divar."

**Comment by mn22nw** [comment]
The arrows should be images of the same style as the blue arrow on base size icon in menu.
