### ISSUE TITLE
Colour on perspectives should be shown with a line underneath the view.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#211]
For the moment the perspectives are shown with a coloured border on the perspective divs. Instead the colour should be shown with a coloured line underneath the view.

**Comment by ba222ec** [comment]
This could be done by moving the coloured line in *ConstructionArea* a bit downwards compared to the base plane.

**Comment by aseea** [comment]
The div should have a bottom border and the perspective-model should move downwards and come as close to the border as possible.
