### ISSUE TITLE
Forms for saving and importing buildings should be styled.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#215]
Error messages should be presented in Swedish. Input field should be bigger. The form should be styled with responsive layout. The forms should have a *Cancel* button. The forms should have an explaining icon instead of a helping text.

**Comment by mn22nw** [comment]
I would like the input-field to have a white background with gray text, so that it doesn't look like a button. 

The input & submit-button jumps down when you get an error message. It would be nicer if message-box was on top of input without pushing it down.

**Comment by davidsoderberg** [comment]
There is now a pull request for that: https://github.com/no222bd/1dv411-Webbprojekt-1/pull/245
