### ISSUE TITLE
Application should have a favicon and an appleicon.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#216]
Application should have a favicon.

**Comment by aseea** [comment]
Maybe a cube? Or maybe that's too plain?

**Comment by ch222kv** [comment]
I'm voting for the cube that is used for "place cube" in the menu, the opposite of "remove cube", but with proper borders so that it looks like our cubes.

**Comment by aseea** [comment]
@ch222kv :+1:

**Comment by davidsoderberg** [comment]
+1

**Comment by ba222ec** [comment]
I agree with ch222kv.

**Comment by mn22nw** [comment]
The favicon will be the same as the color icon.

**Comment by aseea** [comment]
Should have icons for pretty much every device and browser out there.
