### ISSUE TITLE
Perspectives should be placed in a div in the right border of the screen.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#221]
We should move the perspectives from the menu to a div placed in the right side of the screen. It should be possible to hide the perspectives. All five perspectives (top, blue, red, green, yellow) should be visible in the div.

**Comment by ch222kv** [comment]
Removed the pending tag because there are more things to change before it is ready to merge.

**Comment by mn22nw** [comment]
Things to take into consideration when working with this issue from branch "views-visible :

- The view-icon in original menu should not be there anymore regardless of platform and screen size
  (in portrait-mode the view-bar should be at the bottom of the screen)
- The view-bar should hideable (just like counter) and it should be separate from the counter div 
 (so it's possible to hide counter and have the views open and so on)
- For some reason the color-divs are not square anymore
- One view falls outside of the screen on screen format 16:3

**Comment by ch222kv** [comment]
16:3, is that actually real? That would mean that you have a screen of something like 1920 x 360 px, which seems quite odd. Maybe you mean 16:9?

**Comment by ch222kv** [comment]
This issue can now be tested in the views-visible branch. I haven't created a pull request because it isn't really ready to be merged yet, but test it out.
The view bar isn't hidable yet.

**Comment by aseea** [comment]
If you resize the window, topView icon appears in the left menu. And I wonder what happens to the views in portrait mode?

**Comment by aseea** [comment]
Click-events needs to have prevent default. My first thought was to tell you to remove the click-event but its necessary for hiding views later on.

**Comment by mn22nw** [comment]
Yes I mean 16:9 of course XD   lol 

I will take a look at how it looks right now. =)

**Comment by ba222ec** [comment]
Pull request for this issue exists.
