### ISSUE TITLE
Lines get draw in wrong order.

### ISSUE THREAD

**Issue by ch222kv** [no222bd/1dv411-Webbprojekt-1#232]
The lines get drawn in the wrong order, so that the blue line gets drawn instead of the yellow and the red instead of the green. This makes it so that the views looks like they are wrong, but they aren't. 
![Order](http://puu.sh/gnt4f/bee54f14b5.png)
![Order](http://puu.sh/gnt61/7216d51183.png)

As you can see from the images, it's just the lines that are wrong, not the actual perspectives.

#191, #194

**Comment by ba222ec** [comment]
Solved together with issue 211. Coloured lines are hidden by the surrounding div.
