### ISSUE TITLE
Model doesn't show until you resize browser window

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#235]
This is an observation done during tests 5/3-2015 in firefox on a windows machine.

I was not able to recreate the scenario.

**Comment by ch222kv** [comment]
Seems to happen with FF 36  but didn't happen with FF 35. But according to the update notes, there shouldn't be anything that affects our code at all, which is really odd.
Happens for me all the time with FF 36, but any form of the browser window seems to remove the issue.

**Comment by ch222kv** [comment]
Also seems to be a slight flash of the ConstructionArea when you reload the page, but then it sticks to white.

**Comment by aseea** [comment]
That explains it. I have the FF 35 version, updating now...

**Comment by aseea** [comment]
Code in master doesn't show this bug for me anymore.
