### ISSUE TITLE
Flashing occurs in iOS

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#236]
Observations done during tests 5/3-2015.

Flashing appears in safari while adding cubes.
Model surface flashes when the model changes.

**Comment by ch222kv** [comment]
This is still happening? Didn't it get resolved in the #34 issue?
What iOS version, what browser?

**Comment by aseea** [comment]
iOS Firefox & Google Chrome. Guessing the same iOS as last time. It occurred for 2 different individuals.

**Comment by aseea** [comment]
http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/

Maybe this could be something?

**Comment by ch222kv** [comment]
If it is using canvas, and not webgl, then there is no antialias. Maybe this can be solved by using some kind of dubbelbuffer as the last solution did.
