### ISSUE TITLE
Cube sides are not together in iOS 7

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#237]
Observation done during tests 5/3-2015.

Cube sides are not together in iOS 7 in both Chrome and Safari (tablet). This is while using canvas.

**Comment by davidsoderberg** [comment]
Maybe overdraw should be set to an number, please se:
http://stackoverflow.com/questions/16880015/three-js-with-canvas-renderer-broken-textures

**Comment by davidsoderberg** [comment]
There is now a pull request for this issue: https://github.com/no222bd/1dv411-Webbprojekt-1/pull/255.

**Comment by davidsoderberg** [comment]
@mn22nw is this tested so we can close it?
