### ISSUE TITLE
Preview of base in baseSize model does not respect borders of parent div

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#238]
Observartion made during tests 5/3-2015.

iOS, Safari/Google Chrome, Tablet:
The view does not respect the surrounding divs rounded corners.

**Comment by aseea** [comment]
Use !important to style rounded corners on canvas inside preview.

**Comment by davidsoderberg** [comment]
There is now a pull request for this: https://github.com/no222bd/1dv411-Webbprojekt-1/pull/240.
