### ISSUE TITLE
Can't save building with max height.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#246]
When I had a baseSize of 9 and was trying to save a building with the height of 9 cubes, I got message "Försök med ett annat namn :(". The name was a valid name.

**Comment by davidsoderberg** [comment]
Fixed in: https://github.com/no222bd/1dv411-Webbprojekt-1/commit/e7d0011e0d0a5586b5d5ad4fa08e40f25bace10b.
