### ISSUE TITLE
Can add cubes inside cubes.

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#247]
When I was testing the application in commit fa83a3380c4986811e94343b424a264039d565b6 in the master branch, I could add a cube inside another cube. I was viewing the building from above and was clicking rapidly on top of the already added cubes.

**Comment by davidsoderberg** [comment]
I can not recreate this bug...

**Comment by aseea** [comment]
This bug reminds me of the bug we had fixing the uneven base/cubes. I also added uneven base to K1 tests for next week.

**Comment by aseea** [comment]
I could recreate this issue by using an uneven base size but not when having an even base size.

**Comment by aseea** [comment]
Observations done during tests 10/3-2015.

"Den lägger kuber inuti samma kub."
 "Kuber lägga till inuti kuber."
 "Den lägger till fler kuber än den ska, även om dessa inte syns blir det problem när man lägger till. Det blir extra tydligt då räknaren visar fel antal kuber än vad som finns på byggytan (tror givetvis detta har att göra med att man kan lägga till kuber inuti kuber)"
 "Av räknaren att döma så läggs kuber till på redan upptagna platser."

**Comment by ch222kv** [comment]
Since the fix has been merged this issue is now closed.
