### ISSUE TITLE
Modal should close after clearing all cubes

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#249]
Observation done during tests 8/3-2015.

"Borde inte modalen stängas automatiskt efter det att man valt att rensa plattan?"

**Comment by ba222ec** [comment]
I think the modal should close after clearing all cubes since the colour modal and the perspective modal closes automatically.

**Comment by ba222ec** [comment]
Solved with commit 60296eeb6440a9c3d2f0273f998c8dab0b87712b
