### ISSUE TITLE
Takes too long when adding/removing cubes

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#260]
Observations done during tests 10/3-2015.

"Tar hela 3 sekunder från det att man klickat tills dessa att en kub lagts till."
"Samma prestandaproblem som vid lägga till kub. Ca 3 sekunder mellan klick och resultat."

**Comment by aseea** [comment]
More testing is needed on all kinds of platforms. Pay attention and add as many cubes as possible.

**Comment by ch222kv** [comment]
Firefox on Android seems to really dislike setting PixelRatio to lower than what it reports, performance tanks just by setting it to 1, and the quality decreases really much.
Chrome on the other hand thinks different and renders faster, and without that much degradation in quality. 

So setPixelRation should stay the same until further testing proves otherwise.

**Comment by aseea** [comment]
Using the incredibly slow (because it is sadly filled with crap) iconia tab (android):

Browser Canvas: 1 sec delay when placing cubes. Isn't particularly annoying.

Firefox WebGL: When not doing anything at all the stats shows 70~ but sometimes spikes to 100 without any apparent reason. When placing a cube, it goes up to 153 ms. User experience wise there's no delay for me unless i rotate the base. Sometime extreme delay when random color is chosen (spikes to 400 ms).

Chrome WebGL: Resting stats are around 40-50ms, sometimes high spikes. When placing the first cube 800-1000ms. Following cubes 300-450ms. Does not affect user experience. When changing base size down to 9, adding cubes only causes a rise to 200ms. Sometimes feels unresponsive when trying to remove cube.

**Comment by aseea** [comment]
Observations captured during tests 13/3-2015.

(Change color)
Android, Google Chrome, Mobil: "Reagerar långsamt. (stat countern visar 270-300 ms per frame)
Android Opera, Mobil: "Lite hackigt (Stat är 260-280 ms)"

(Add cube even/uneven)
Android, Google Chrome, Mobil: "Långsamt", "Långsamt (stat = 280-300 ms/frame)"
Android Opera, Mobil: "Lite långsamt.", "Lite långsamt."

(Remove cube)
Android, Google Chrome, Mobil: "Långsamt (stat = 280-300 ms/frame)"
Android Opera, Mobil: "Lite långsamt."

(Rotating)
Android, Google Chrome, Mobil: "Långsamt. Dock så står stat countern på samma värde som när modellen är stilla, ingen top vid rotering."
Android Opera, Mobil: "Lite långsamt."

(Zooming)
Android, Google Chrome, Mobil: "Långsamt. Stat counter toppar till ca 1000 ms per frame vid zoom.", "Zoomen flyter på bra i Chrome."
Android Opera, Mobil: "Lite långsamt."

(Comments)
Android, Google Chrome, Mobil: "Fungerar bättre i Chrome än i Firefox. Bättre flyt, mindre lagg.", "Långssam. Laggar mycket och inte tillräckligt snabb för att egentligen fungera på mobil.", "Fungerar mycket bra på Chrome."
Android Opera, Mobil: "Lite långsam och hackig."

**Comment by ba222ec** [comment]
Most of the comments above are written by me, using a Samsung Galaxy s3.
