### ISSUE TITLE
Preview of base size is bugged

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#282]
Observations done during tests 13/3-2015.

"Storleken ändras men previewen är helt tom."
"Går att ändra storlek, men previewn hänger inte med."
"Storleken ökar, men previewn visar ingenting."
"Fungerar, men previewn visar ingenting..."
"Lite långsam och hackig. Preview-vyn som synd i resizemodalen hänger inte med och visar ofta fel. När man lägger till/tar bort ett block så händer det först ingenting, sen uppdaretas alla vyerna och byggnaden samtidigt. Det kan vara så att långsamheten ligger i koden i three.js och att vår egen kod egentligen kör tillräckligt snabbt, eftersom alla vyerna och byggnaden uppdateras samtidigt."
"Basen rensas och modalen stängs. Men previewn visar fel basplatta eller ingenting alls."

**Comment by ba222ec** [comment]
This was happening on Samsung Galaxy S3.

**Comment by ch222kv** [comment]
Has this been tested as of lately? With the updated optimization code, this should not be happening.
