### ISSUE TITLE
Base size arrows/buttons styling is wrong

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#284]
Observations done during tests 13/3-2015.

"Knapparna hamnar lite utanför här också, men inte lika mycket som i Firefox, enbart några få pixlar för långt ner."
"Pilarna flyter lite nedåt i knapparna, så att de inte riktigt rymms i knapparnas storlek."

**Comment by ch222kv** [comment]
Looks good for me, merging.
