### ISSUE TITLE
Zoom out

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#285]
Observations done during tests 13/3-2015.

"Vid en storlek på mindre än 7 så går det inte att zooma ut.Finns kanske inget behov av detta dock."
"Med basplatta mindre än 7 i bredd så går det inte att zooma ut ifrån ursprungsläget."
"Dock ej möjligt om basplattan är mindre än 7 i bredd."

**Comment by aseea** [comment]
I see no need to zoom out more when base size is 7.

**Comment by ba222ec** [comment]
The existing function works.
