### ISSUE TITLE
Difficult to zoom using Firefox (smartphone?)

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#286]
Observations done during tests 13/3-2015.

"Väldigt svårt att zooma i firefox, går praktiskt taget inte alls."

**Comment by ch222kv** [comment]
This is using smartphone yes, but Firefox seems reluctant to run our application at all, so it might not be such a big problem anyway.

**Comment by ba222ec** [comment]
We will not fix this issue.
