### ISSUE TITLE
Mirrored views

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#287]
Observations done during tests 13/3-2015.

"Fortfarande spegelvända/fel vy."
"Har rensat cashen och när jag sparar som bokmärke så visas version 0.8. Ändå så är vyerna förväxlade."
"Trots att cashen är rensad och titelraden visar 0.8 så är vyerna förväxlade."

**Comment by aseea** [comment]
I don't see any problem with the views what so ever in the 0.8 version. Same with the current master-code.

**Comment by ba222ec** [comment]
Issue appear on browsers: *Chrome on iOS*, *Dolphin*, *Safari on iOS*.

Try adding prefix -ms-, -moz-, -webkit- on css rule *transform*.
