### ISSUE TITLE
Counter doesn't show in portrait mode

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#288]
Observations done during tests 13/3-2015.

"Ej i porträttläge."
"Visas ej i porträttläge."
"Fungerar inte i portrait-mode då räknaren inte syns."
"Fungerar inte i portrait-mode då räknaren försvinner."

**Comment by ba222ec** [comment]
Solved with a23168a50012fec1079b71a95c1ddc372f8da720
