### ISSUE TITLE
Button to hide counter/views disappears in portrait

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#291]
Observation done during tests 13/3-2015.

"I porträttläge så hamnar knappen för att dölja räknaren fel och knappen för att dölja vyerna försvinner. Reducerar man bredden ytterligare så blir det korrekt varför det måste bero på en miss i mediaquery."
"Fel i knapparna för att visa/dölja räknare/vyer i porträttläget."

**Comment by ba222ec** [comment]
This happends if screen width is bigger than 700 and in portrait mode. e should support portrait mode with max-witdh: 1536 (height of iPad).

**Comment by ba222ec** [comment]
Solved with a23168a50012fec1079b71a95c1ddc372f8da720
