### ISSUE TITLE
Android, Google Chrome, Mobil

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#294]
Observation done during tests 13/3-2015.

"Ingenting alls händer när man klickar på "Hämta". Inget meddelande, modalen är fortfarande kvar."
"Händer ingenting alls när jag klickar på "Hämta". Kan det vara något med avsaknad av localStorage?"
T3.4b: "Ingenting alls händer när jag klickar på "Spara"."

**Comment by aseea** [comment]
In my htc one (android smartphone), using google chrome works fine when it comes to saving and opening a saved model. Offline as well as online.

**Comment by ba222ec** [comment]
This errors happend on Samsung Galaxy S3.
