### ISSUE TITLE
Problem with the placement of cubes

### ISSUE THREAD

**Issue by ch222kv** [no222bd/1dv411-Webbprojekt-1#3]
The Babylon example is very imprecise in where it places the cubes. Sometimes it will place the cube where your mouse cursor is, and sometimes it will place it somewhere else. 

See https://www.youtube.com/watch?v=4UvfikYvDA0 for an example.

**Comment by davidsoderberg** [comment]
Yes, that is a known problem to me. 
All cubes in model har hidden and when a click event happens babylon picks the cube that are in the x and y axis. Maybe we need  another technique to pick the correct cube?
