### ISSUE TITLE
Error message smiley smiling when should be sad

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#316]
If you save model and after it gives you a success message, you try to save again, the message showing will be "Namnet finns redan" but the smiley will remain the happy one.

**Comment by ba222ec** [comment]
This happends only if you do two saving/getting actions in a row without closing the modal in between.

**Comment by ba222ec** [comment]
Solved with 913acc58bb03917e83ed02d253fec45ac692e24b
