### ISSUE TITLE
Black flash appears when adding cubes on iPad iOS 7.1.2 and 8

### ISSUE THREAD

**Issue by mn22nw** [no222bd/1dv411-Webbprojekt-1#34]
Happens about every second time a cube is added.
Takes too long to render?

**Comment by no222bd** [comment]
No issue on iPad 4 with iOS 8.1.3

**Comment by ch222kv** [comment]
Has someone tried this as of lately? With a stats counter to display the FPS?

**Comment by no222bd** [comment]
Flickering problem now present in iOS8 as well.

**Comment by aseea** [comment]
http://caniuse.com/#feat=webgl

**Comment by mn22nw** [comment]
If we can't fix this for canvas....A solution could be to add a message that says something like
"For best performance please update your device to the latest version. (If you don't you might experience black flashes when adding cubes)"

**Comment by ba222ec** [comment]
Problem with black flashing on Samsung Galazy S3 Chrome is solved. It's not blinking and flashing on this platform any more.
