### ISSUE TITLE
renderPerspectives creates new renderers.

### ISSUE THREAD

**Issue by ch222kv** [no222bd/1dv411-Webbprojekt-1#48]
When you open the modal it calls the function ```renderPerspectives```. This function then calls the function ```renderPerspectives``` on the ```BUILDER.ConstructionArea``` object. However, that function doesn't render the perspectives, it creates them. That means that the code creates a lot of new render areas when you open the modal instead of just display the old ones. 

What needs to be done is a function that does 
```javascript
views.forEach(function(element, index, array) {
				element.render();
			});
``` 
instead of creating new renderers.

**Comment by aseea** [comment]
Created a function called createPerspectives that runs through ConstructionArea.init. The UI then calls renderPerspectives just like the example above.
