### ISSUE TITLE
Make init a public function and do not init when including the page.

### ISSUE THREAD

**Issue by ch222kv** [no222bd/1dv411-Webbprojekt-1#78]
It makes more sense to have the init function be called explicitly when you create the object on the page instead of just going ahead a running the code directly when you include the js on the page.

**Comment by davidsoderberg** [comment]
I do not think I understand what you try to explain...!

**Comment by ch222kv** [comment]
```new BUILDER.CubeBuilder``` creates a new CubeBuilder object, which in hand runs the init function. It would make more sense to have the init function be a public function that you must call explicitly.

```javascript
var cb = new BUILDER.CubeBuilder();
```

would turn into
```javascript
var cb = new BUILDER.CubeBuilder();
cb.init();
```

**Comment by davidsoderberg** [comment]
I think of init as an constructor so it makes sense to me to not need to call it, what do you think?

**Comment by aseea** [comment]
We could make it a prototype?

**Comment by davidsoderberg** [comment]
But is that a standard way to have it if we think of it as a constructor?

**Comment by aseea** [comment]
I believe so. At least that's how I was thaught to do constructors in JavaScript but I'm no expert. This requires research about standards.
