### ISSUE TITLE
ToggleBuildMode should take a parameter

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#80]
Should take true or false as a parameter to prevent bugs in the UI. Optional; create a method to disable link in index.html (proven difficult).

**Comment by ch222kv** [comment]
How do you mean?
```javascript
this.toggleBuildMode = function(build){
    ...
}
```

or do you need a way to get the buildMode? 
```javascript
this.getBuildMode = function(){
    ...
}
```
?

**Comment by aseea** [comment]
Best way to describe the problem is to run the code in the master branch and press cube-icon twice. :)

**Comment by davidsoderberg** [comment]
I think this problem is solved, am I wrong?

**Comment by davidsoderberg** [comment]
This problem has been solved.
