### ISSUE TITLE
Green foundation (color on base plane) covers added cubes in top perspective view.

### ISSUE THREAD

**Issue by mn22nw** [no222bd/1dv411-Webbprojekt-1#83]
If base plane foundation is visible in canvas renderer, top view perspective isn't working. The foundation color covers the added cubes and you can't see the cubes in the top view perspective.

**Comment by ch222kv** [comment]
What does "not work" mean? Do you mean the clipping that happens where the cubes gets hidden by the base plate, or something else?

**Comment by mn22nw** [comment]
yep!  and the same clipping happened when I tried having an image as foundation...

**Comment by davidsoderberg** [comment]
Maybe we should have transparent foundation?

**Comment by mn22nw** [comment]
maybe we could have transparent for canvas? and green for webGL?

**Comment by davidsoderberg** [comment]
@mn22nw: what hex was the green color?

**Comment by aseea** [comment]
Reopen issue while implementing fix for perspective views (canvas). Perspectives display the green foundation faulty because browser supports webGL but not the canvas renderers.

**Comment by aseea** [comment]
This issue might get fixed in the future.
