### ISSUE TITLE
Missing tests in createPerspectivesSpec

### ISSUE THREAD

**Issue by ba222ec** [no222bd/1dv411-Webbprojekt-1#85]
We need to add tests for checking that views have correct JQueryElement. This should be added when dependency problem between the model and the view is fixed.

**Comment by davidsoderberg** [comment]
Both @aseea and I do this now :smile:

**Comment by davidsoderberg** [comment]
Fixed in commit: https://github.com/no222bd/1dv411-Webbprojekt-1/commit/82163af2510e3587d8ae04800ecf6cd992d04d43.
