### ISSUE TITLE
Perspective topview is viewed from the wrong angle

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#87]
Adding -1000 or 1000 as y-parameter on line 393 fixes problem but then CSS/html needs to change so it works with the colored lines. We also need to discuss the matter of lights and think about if we should have them shining from underneath the base upwards.

**Comment by ba222ec** [comment]
Solved with commit e8347f0c01b87877e807fe61f54c7097a203587b
